version: "3.7"

services:
  postgres:
    container_name: animal-shelter-database
    image: postgres:14.5-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'Europe/Paris'
      PGTZ: 'Europe/Paris'